Basicos de numpy para data analyst

In [1]:
# Importamos la librería numpy
import numpy as np

In [2]:
# 1. Crear arrays (vectores)
a = np.array([1, 2, 3, 4, 5])  # Vector de una dimensión
print("Vector a:", a)

# Array bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatriz 2x3:")
print(matriz)

Vector a: [1 2 3 4 5]

Matriz 2x3:
[[1 2 3]
 [4 5 6]]


In [3]:
# 2. Crear arrays especiales

ceros = np.zeros(5)         # [0. 0. 0. 0. 0.]
unos = np.ones((2, 3))      # Matriz 2x3 llena de 1s
rango = np.arange(0, 10, 2) # [0 2 4 6 8]
aleatorios = np.random.rand(3, 2)  # Matriz 3x2 con números aleatorios [0,1)

print("\nArray de ceros:", ceros)
print("Array de unos:\n", unos)
print("Rango:", rango)
print("Array aleatorio 3x2:\n", aleatorios)


Array de ceros: [0. 0. 0. 0. 0.]
Array de unos:
 [[1. 1. 1.]
 [1. 1. 1.]]
Rango: [0 2 4 6 8]
Array aleatorio 3x2:
 [[0.60674181 0.16900054]
 [0.9242963  0.81038341]
 [0.73013232 0.47857416]]


In [4]:
# 3. Operaciones básicas

b = np.array([10, 20, 30, 40, 50])

print("\nSuma de vectores:", a + b)        # [11 22 33 44 55]
print("Resta:", b - a)                     # [ 9 18 27 36 45]
print("Producto elemento a elemento:", a * b)
print("División:", b / a)


Suma de vectores: [11 22 33 44 55]
Resta: [ 9 18 27 36 45]
Producto elemento a elemento: [ 10  40  90 160 250]
División: [10. 10. 10. 10. 10.]


In [5]:
# 4. Estadísticas básicas

print("\nPromedio (mean) de a:", np.mean(a))
print("Mediana (median) de b:", np.median(b))
print("Desviación estándar:", np.std(b))
print("Suma total:", np.sum(b))



Promedio (mean) de a: 3.0
Mediana (median) de b: 30.0
Desviación estándar: 14.142135623730951
Suma total: 150


In [6]:
# 5. Índices y slicing

print("\nPrimer elemento de a:", a[0])
print("Últimos 3 elementos de b:", b[-3:])
print("Submatriz (2x2):\n", matriz[:, :2])  # Dos primeras columnas


Primer elemento de a: 1
Últimos 3 elementos de b: [30 40 50]
Submatriz (2x2):
 [[1 2]
 [4 5]]


In [7]:
# 6. Cambiar la forma del array

print("\nForma original de matriz:", matriz.shape)  # (2, 3)
matriz_reshaped = matriz.reshape((3, 2))
print("Matriz con nueva forma 3x2:\n", matriz_reshaped)


Forma original de matriz: (2, 3)
Matriz con nueva forma 3x2:
 [[1 2]
 [3 4]
 [5 6]]


In [8]:
# 7. Concatenar arrays

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
concatenado = np.concatenate((x, y))
print("\nArrays concatenados:", concatenado)


Arrays concatenados: [1 2 3 4 5 6]


In [9]:
# 8. Comparaciones lógicas

print("\n¿a > 2?:", a > 2)             # Devuelve array de booleanos
print("Elementos mayores a 2:", a[a > 2])  # Filtra los valores


¿a > 2?: [False False  True  True  True]
Elementos mayores a 2: [3 4 5]


Concepto	            ¿Qué deberías saber?

np.array	            Crear vectores o matrices
np.mean, np.std	        Calcular estadísticas rápidas
reshape	                Cambiar la forma de un array
random.rand, arange	    Crear arrays rápidos (aleatorios o secuenciales)
Operaciones +, *, etc.	Operar arrays como si fueran vectores matemáticos